version: "3"

services:
  web:
    build: .
    command: >
      bash -c '
        python financial/manage.py makemigrations
        python financial/manage.py migrate
        python financial/manage.py runserver 0.0.0.0:5000'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    healthcheck:
      # Test the health endpoint
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    # command: >
    #   bash -c '
    #     until echo "SELECT 1" | mysql -hdb -uroot -p"$MYSQL_ROOT_PASSWORD" &> /dev/null
    #     do
    #       >&2 echo "MySQL is unavailable - sleeping"
    #       sleep 1
    #     done
    #     >&2 echo "MySQL is up - executing command"
    #     mysql -hdb -uroot -p"$MYSQL_ROOT_PASSWORD" -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY '\''${MYSQL_ROOT_PASSWORD}'\'';"'
