name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master

env:
  IMAGE_TAG: latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag python_assignment_web:latest "${{ secrets.DOCKER_USERNAME }}/financial-web:${IMAGE_TAG}"
          docker push "${{ secrets.DOCKER_USERNAME }}/financial-web:${IMAGE_TAG}"

      # - name: Upload docker image
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docker images for financial servers
      #     path: |
      #       python_assignment_web

      # - name: Download docker image
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: python_assignment_web
