name: Test Financial Data APIs

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      run: |
        export TEST_DATABASE=ON
        python financial/manage.py makemigrations
        python financial/manage.py migrate

    - name: Run web server tests
      run: |
        export TEST_DATABASE=ON
        python financial/manage.py test core.tests

    - name: Run tests for get_raw_data
      run: |
        python -m unittest tests/test_get_raw_data.py
